version: '2.4'

services:

  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    expose:
      - 7474
    container_name: neo4j_docker
    network_mode: "host"
    hostname: localhost
    restart: always
    volumes:
      - /neo4j/data:/data
      - ./neo4j/import:/import
    environment:
      - NEO4J_AUTH=neo4j/1234


  manual-answer:
    build: manual-answer-service/
    restart: always
    network_mode: "host"
    image: manual-answer-service
    hostname: localhost
    ports:
      - 8091:8091
    mem_limit: 300m
    mem_reservation: 300m

  user-service:
    build: user-service/
    restart: always
    network_mode: "host"
    image: user-service
    hostname: localhost
    ports:
      - 8081:8081
    mem_limit: 200m
    mem_reservation: 200m


  oraclefrontend:
    build: oracle-frontend/
    image: oracle-frontend:latest
    container_name: oracle-frontend
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200
    restart: always

  bot-service:
    build: bot-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8090:8090


  queryautocorrector-service:
    build: queryautocorrector-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8595:8595
    mem_limit: 300m

  graph-query-service:
    build: graph-query-service/
    image: graph-query-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8082:8082


  extract-intent-service:
    build: extract-intent-service/
    image: extract-intent-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8383:8383

  timeseries-conversation-service:
    build: timeseries-conversation-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9000:9000
    mem_limit: 300m